### ISSUE TITLE
[RegistrySync] Crash when load an existing world with a new mod with additional blocks or items

### ISSUE THREAD

**Issue by arthurbambou** [Legacy-Fabric/fabric#133]
```
[18:57:56] [Client thread/INFO]: Client started
[18:57:58] [Client thread/INFO]: Remapping registry minecraft:items
[18:57:58] [Client thread/INFO]: Adding 2 missing entries to registry
[18:57:58] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.class_875: Updating screen events
	at net.minecraft.class_1600.method_2954(class_1600.java:1508) ~[client-intermediary.jar:?]
	at net.minecraft.class_1600.method_2916(class_1600.java:889) ~[client-intermediary.jar:?]
	at net.minecraft.class_1600.method_5580(class_1600.java:325) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:124) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_322]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_322]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_322]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_322]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Remapping world failed!
	at net.minecraft.class_98.handler$zbg000$readWorldProperties(class_98.java:648) ~[client-intermediary.jar:?]
	at net.minecraft.class_98.method_245(class_98.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1600.method_6636(class_1600.java:1902) ~[client-intermediary.jar:?]
	at net.minecraft.class_391.method_1079(class_391.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_391$class_392.method_1057(class_391.java:224) ~[client-intermediary.jar:?]
	at net.minecraft.class_390.method_9529(class_390.java:315) ~[client-intermediary.jar:?]
	at net.minecraft.class_391.method_1035(class_391.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_388.method_1039(class_388.java:390) ~[client-intermediary.jar:?]
	at net.minecraft.class_1600.method_2954(class_1600.java:1498) ~[client-intermediary.jar:?]
	... 14 more
Caused by: java.lang.IllegalArgumentException: value already present: 9
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238) ~[guava-17.0.jar:?]
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215) ~[guava-17.0.jar:?]
	at net.legacyfabric.fabric.impl.registry.sync.RegistryRemapper.lambda$dump$0(RegistryRemapper.java:54) ~[legacy-fabric-registry-sync-api-+ae14835439-2d7f8766ac2c751a.jar:?]
	at java.util.IdentityHashMap.forEach(IdentityHashMap.java:1358) ~[?:1.8.0_322]
	at net.legacyfabric.fabric.impl.registry.sync.RegistryRemapper.dump(RegistryRemapper.java:52) ~[legacy-fabric-registry-sync-api-+ae14835439-2d7f8766ac2c751a.jar:?]
	at net.legacyfabric.fabric.impl.registry.sync.RegistryRemapper.remap(RegistryRemapper.java:106) ~[legacy-fabric-registry-sync-api-+ae14835439-2d7f8766ac2c751a.jar:?]
	at net.legacyfabric.fabric.impl.registry.sync.RegistryRemapperAccess.remap(RegistryRemapperAccess.java:36) ~[legacy-fabric-registry-sync-api-+ae14835439-2d7f8766ac2c751a.jar:?]
	at net.legacyfabric.fabric.impl.registry.sync.RegistryRemapperAccess.readAndRemap(RegistryRemapperAccess.java:43) ~[legacy-fabric-registry-sync-api-+ae14835439-2d7f8766ac2c751a.jar:?]
	at net.minecraft.class_98.fabric_readIdMapFile(class_98.java:567) ~[client-intermediary.jar:?]
	at net.minecraft.class_98.handler$zbg000$readWorldProperties(class_98.java:635) ~[client-intermediary.jar:?]
	at net.minecraft.class_98.method_245(class_98.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1600.method_6636(class_1600.java:1902) ~[client-intermediary.jar:?]
	at net.minecraft.class_391.method_1079(class_391.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_391$class_392.method_1057(class_391.java:224) ~[client-intermediary.jar:?]
	at net.minecraft.class_390.method_9529(class_390.java:315) ~[client-intermediary.jar:?]
	at net.minecraft.class_391.method_1035(class_391.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_388.method_1039(class_388.java:390) ~[client-intermediary.jar:?]
	at net.minecraft.class_1600.method_2954(class_1600.java:1498) ~[client-intermediary.jar:?]
	... 14 more
```

**Comment by arthurbambou** [comment]
Fixed in 1.7.0
