### ISSUE TITLE
When I start "runClient",It Will be crash.

### ISSUE THREAD

**Issue by ypo-GitHub** [Legacy-Fabric/fabric#144]
```> Task :runClient
[12:53:48] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.8.9 with Fabric Loader 0.14.12
[12:53:48] [main/INFO] (FabricLoader) Loading 29 mods:
	- fabricloader 0.14.12
	- java 17
	- legacy-fabric-api 1.9.0+1.8.9
	- legacy-fabric-api-base 1.1.0+1.8.9+f368a06d39
	- legacy-fabric-api-base-common 1.1.0+1dd3cad892
	- legacy-fabric-command-api-v1 1.0.0+ae4aa0d092
	- legacy-fabric-command-api-v2 1.0.0+1.8.9+01f7587839
	- legacy-fabric-crash-report-info-v1 1.0.0+1.8.9+f368a06d39
	- legacy-fabric-entity-events-v1-common 1.0.0+ae4aa0d092
	- legacy-fabric-fixes 1.0.0+1.8.9+f368a06d39
	- legacy-fabric-gamerule-api-v1 1.0.0+ae4aa0d092
	- legacy-fabric-item-groups-v1 2.0.0+1.8.9+f368a06d39
	- legacy-fabric-item-groups-v1-common 2.0.0+1dd3cad892
	- legacy-fabric-keybinding-api-v1-common 1.0.0+ae4aa0d092
	- legacy-fabric-lifecycle-events-v1 1.0.1+1.8.9+d86bee7939
	- legacy-fabric-lifecycle-events-v1-common 1.0.1+ae4aa0d092
	- legacy-fabric-logger-api-v1 1.0.4+ae4aa0d092
	- legacy-fabric-networking-api-v1 2.0.0+1.8.9+01f7587839
	- legacy-fabric-networking-api-v1-common 2.0.0+022f9a7592
	- legacy-fabric-permissions-api-v1 1.0.0+1.8.9+f368a06d39
	- legacy-fabric-permissions-api-v1-common 1.0.0+ae4aa0d092
	- legacy-fabric-registry-sync-api-v1 2.1.0+1.8.9+508c546039
	- legacy-fabric-registry-sync-api-v1-common 2.1.0+508c546092
	- legacy-fabric-rendering-api-v1 1.0.0+1.8.9+022f9a7539
	- legacy-fabric-rendering-api-v1-common 1.0.0+ae4aa0d092
	- legacy-fabric-resource-loader-v1 2.1.0+1.8.9+022f9a7539
	- legacy-fabric-resource-loader-v1-common 2.1.0+a9c128f492
	- minecraft 1.8.9
	- modid 1.0.0
[12:53:48] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/Monika/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/c1dc27696aa4006e492c2485c9ccbcb26045a971/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[12:53:48] [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper!
Completely ignored arguments: [--versionType, Fabric]
[12:53:49] [main/INFO] (Minecraft) Setting user: Player450
[12:53:49] [main/INFO] (Minecraft) (Session ID is token:FabricMC:Player450)
Hello Fabric world!
[12:53:50] [main/INFO] (Minecraft) LWJGL Version: 2.9.4-babric.1
[12:53:51] [main/INFO] (Minecraft) Reloading ResourceManager: Default, Legacy Fabric Registry Sync API (V1), Legacy Fabric Lifecycle Events (V1), Legacy Fabric Keybinding API (V1), Fabric Gamerule API (v1), Legacy Fabric Networking API (v1), Legacy Fabric API Base, Legacy Fabric Command API (v2), Legacy Fabric Command API (V1), Legacy Fabric API, Fabric Loader, Legacy Fabric Crash Report Info (v1), Legacy Fabric Registry Sync API (V1), Legacy Fabric Logger API (v1), Legacy Fabric Item Groups (V1), Legacy Fabric Lifecycle Events (V1), Legacy Fabric Entity Events (V1), Legacy Fabric Rendering API (V1), Legacy Fabric API Base Common, Legacy Fabric Permissions API (v1), Legacy Fabric Networking API (v1), Legacy Fabric Permissions API (v2), Legacy Fabric Rendering API (V1), Legacy Fabric Resource Loader (V1) Common, Example Mod, Legacy Fabric Item Groups (V1), Legacy Fabric Fixes, Legacy Fabric Resource Loader (V1)
If on Windows, make sure to provide all of the necessary dll's as specified in the twitchsdk README. Also, make sure to set the PATH environment variable to point to the directory containing the dll's.
[12:53:51] [main/ERROR] (Minecraft) Couldn't initialize twitch stream
[12:53:51] [Sound Library Loader/INFO] (Minecraft) Starting up SoundSystem...
[12:53:51] [Thread-4/INFO] (Minecraft) Initializing LWJGL OpenAL
[12:53:51] [Thread-4/INFO] (Minecraft) (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[12:53:51] [Thread-4/INFO] (Minecraft) OpenAL initialized.
[12:53:52] [Sound Library Loader/INFO] (Minecraft) Sound engine started
[12:53:53] [main/INFO] (Minecraft) Created: 512x512 textures-atlas
This line is printed by an example mod mixin!
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023/1/22 下午12:53
Description: Initializing game

java.lang.NoSuchMethodError: 'void com.mojang.realmsclient.gui.screens.RealmsNotificationsScreen.buttonsClear()'
	at com.mojang.realmsclient.gui.screens.RealmsNotificationsScreen.init(RealmsNotificationsScreen.java:38)
	at net.minecraft.client.realms.RealmsScreenProxy.init(RealmsScreenProxy.java:40)
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen.java:208)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:376)
	at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient.java:819)
	at net.minecraft.client.MinecraftClient.initializeGame(MinecraftClient.java:476)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:310)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mojang.realmsclient.gui.screens.RealmsNotificationsScreen.init(RealmsNotificationsScreen.java:38)
	at net.minecraft.client.realms.RealmsScreenProxy.init(RealmsScreenProxy.java:40)
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen.java:208)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:376)
	at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient.java:819)
	at net.minecraft.client.MinecraftClient.initializeGame(MinecraftClient.java:476)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:310)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 5.15.77-amd64-desktop
	Java Version: 17.0.6, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 231033040 bytes (220 MB) / 494927872 bytes (472 MB) up to 4169138176 bytes (3976 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Fabric Mods: 
		fabricloader: Fabric Loader 0.14.12
		java: OpenJDK 64-Bit Server VM 17
		legacy-fabric-api: Legacy Fabric API 1.9.0+1.8.9
		legacy-fabric-api-base: Legacy Fabric API Base 1.1.0+1.8.9+f368a06d39
		legacy-fabric-api-base-common: Legacy Fabric API Base Common 1.1.0+1dd3cad892
		legacy-fabric-command-api-v1: Legacy Fabric Command API (V1) 1.0.0+ae4aa0d092
		legacy-fabric-command-api-v2: Legacy Fabric Command API (v2) 1.0.0+1.8.9+01f7587839
		legacy-fabric-crash-report-info-v1: Legacy Fabric Crash Report Info (v1) 1.0.0+1.8.9+f368a06d39
		legacy-fabric-entity-events-v1-common: Legacy Fabric Entity Events (V1) 1.0.0+ae4aa0d092
		legacy-fabric-fixes: Legacy Fabric Fixes 1.0.0+1.8.9+f368a06d39
		legacy-fabric-gamerule-api-v1: Fabric Gamerule API (v1) 1.0.0+ae4aa0d092
		legacy-fabric-item-groups-v1: Legacy Fabric Item Groups (V1) 2.0.0+1.8.9+f368a06d39
		legacy-fabric-item-groups-v1-common: Legacy Fabric Item Groups (V1) 2.0.0+1dd3cad892
		legacy-fabric-keybinding-api-v1-common: Legacy Fabric Keybinding API (V1) 1.0.0+ae4aa0d092
		legacy-fabric-lifecycle-events-v1: Legacy Fabric Lifecycle Events (V1) 1.0.1+1.8.9+d86bee7939
		legacy-fabric-lifecycle-events-v1-common: Legacy Fabric Lifecycle Events (V1) 1.0.1+ae4aa0d092
		legacy-fabric-logger-api-v1: Legacy Fabric Logger API (v1) 1.0.4+ae4aa0d092
		legacy-fabric-networking-api-v1: Legacy Fabric Networking API (v1) 2.0.0+1.8.9+01f7587839
		legacy-fabric-networking-api-v1-common: Legacy Fabric Networking API (v1) 2.0.0+022f9a7592
		legacy-fabric-permissions-api-v1: Legacy Fabric Permissions API (v2) 1.0.0+1.8.9+f368a06d39
		legacy-fabric-permissions-api-v1-common: Legacy Fabric Permissions API (v1) 1.0.0+ae4aa0d092
		legacy-fabric-registry-sync-api-v1: Legacy Fabric Registry Sync API (V1) 2.1.0+1.8.9+508c546039
		legacy-fabric-registry-sync-api-v1-common: Legacy Fabric Registry Sync API (V1) 2.1.0+508c546092
		legacy-fabric-rendering-api-v1: Legacy Fabric Rendering API (V1) 1.0.0+1.8.9+022f9a7539
		legacy-fabric-rendering-api-v1-common: Legacy Fabric Rendering API (V1) 1.0.0+ae4aa0d092
		legacy-fabric-resource-loader-v1: Legacy Fabric Resource Loader (V1) 2.1.0+1.8.9+022f9a7539
		legacy-fabric-resource-loader-v1-common: Legacy Fabric Resource Loader (V1) Common 2.1.0+a9c128f492
		minecraft: Minecraft 1.8.9
		modid: Example Mod 1.0.0
	Launched Version: Fabric
	LWJGL: 2.9.4-babric.1
	OpenGL: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 510.73.08, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
#@!@# Game crashed! Crash report saved to: #@!@# /media/Monika/这是个卷标/EnjoyFight/run/crash-reports/crash-2023-01-22_12.53.53-client.txt
[12:53:53] [Client Shutdown Thread/INFO] (Minecraft) Stopping server
AL lib: (EE) alc_cleanup: 1 device not closed

> Task :runClient FAILED

Execution failed for task ':runClient'.
> Process 'command '/home/Monika/.jdks/corretto-17.0.6/bin/java'' finished with non-zero exit value 255

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.


```

**Comment by arthurbambou** [comment]
What version of yarn/mappings are you using?

**Comment by ypo-GitHub** [comment]
> What version of yarn/mappings are you using?

	minecraft_version = 1.8.9
	yarn_mappings = 1.8.9+build.451
	loader_version = 0.14.12

**Comment by ypo-GitHub** [comment]
I tried to find "void com.mojang.realmsclient.gui.screens.RealmsNotificationsScreen.buttonsClear()"with idea decompiler but I can't find "void com.mojang.realmsclient.gui.screens.RealmsNotificationsScreen.buttonsClear()"

**Comment by BleachDev** [comment]
Switch to build 458 of the mappings, pretty sure this was a yarn issue.

**Comment by ypo-GitHub** [comment]
thanks it's work
