### ISSUE TITLE
[1.8-1.9] The sign cannot run commands

### ISSUE THREAD

**Issue by Lonmo0208** [Legacy-Fabric/fabric#151]
[message.txt](https://github.com/Legacy-Fabric/fabric/files/14186409/message.txt)
![NO ADD API](https://github.com/Legacy-Fabric/fabric/assets/95102577/e8e8fdc2-fe3c-445b-9289-3cac74cdd4c1)
![YES ADD API](https://github.com/Legacy-Fabric/fabric/assets/95102577/f12c9798-b10b-4d8b-a85e-ec50ad729d94)

**Comment by Lonmo0208** [comment]
![Uploading NO ADD API.gif…]()

**Comment by Lonmo0208** [comment]
![Uploading YES ADD API.gif…]()

**Comment by Lonmo0208** [comment]
Mixin apply for mod legacy-fabric-permissions-api-v1 failed legacy-fabric-permissions-api-v1.mixins.json:SignBlockEntity_2Mixin from mod legacy-fabric-permissions-api-v1 -> net.minecraft.class_224$2: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field editor was not located in the target class net.minecraft.class_224$2. Using refmap legacy-fabric-permissions-api-v1-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field editor was not located in the target class net.minecraft.class_224$2. Using refmap legacy-fabric-permissions-api-v1-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.1.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) [?:?]
	at net.minecraft.class_224.method_8995(class_224.java:141) [client-intermediary.jar:?]
	at net.minecraft.class_184.method_421(class_184.java:83) [client-intermediary.jar:?]
	at net.minecraft.class_799.method_2170(class_799.java:292) [client-intermediary.jar:?]
	at net.minecraft.class_2107.method_7947(class_2107.java:507) [client-intermediary.jar:?]
	at net.minecraft.class_731.method_8037(class_731.java:59) [client-intermediary.jar:?]
	at net.minecraft.class_731.method_1831(class_731.java:10) [client-intermediary.jar:?]
	at net.minecraft.class_2570$1.run(class_2570.java:22) [client-intermediary.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.minecraft.class_1723.method_10652(class_1723.java:19) [client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3046(MinecraftServer.java:579) [client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3044(MinecraftServer.java:535) [client-intermediary.jar:?]
	at net.minecraft.class_601.method_3044(class_601.java:281) [client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:451) [client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
[04:49:27] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_224$2 failed
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at net.minecraft.class_1723.method_10652(class_1723.java:20) [client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3046(MinecraftServer.java:579) [client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3044(MinecraftServer.java:535) [client-intermediary.jar:?]
	at net.minecraft.class_601.method_3044(class_601.java:281) [client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:451) [client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_224$2 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at net.minecraft.class_224.method_8995(class_224.java:141) ~[client-intermediary.jar:?]
	at net.minecraft.class_184.method_421(class_184.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_799.method_2170(class_799.java:292) ~[client-intermediary.jar:?]
	at net.minecraft.class_2107.method_7947(class_2107.java:507) ~[client-intermediary.jar:?]
	at net.minecraft.class_731.method_8037(class_731.java:59) ~[client-intermediary.jar:?]
	at net.minecraft.class_731.method_1831(class_731.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_2570$1.run(class_2570.java:22) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.class_1723.method_10652(class_1723.java:19) ~[client-intermediary.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at net.minecraft.class_224.method_8995(class_224.java:141) ~[client-intermediary.jar:?]
	at net.minecraft.class_184.method_421(class_184.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_799.method_2170(class_799.java:292) ~[client-intermediary.jar:?]
	at net.minecraft.class_2107.method_7947(class_2107.java:507) ~[client-intermediary.jar:?]
	at net.minecraft.class_731.method_8037(class_731.java:59) ~[client-intermediary.jar:?]
	at net.minecraft.class_731.method_1831(class_731.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_2570$1.run(class_2570.java:22) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.class_1723.method_10652(class_1723.java:19) ~[client-intermediary.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [legacy-fabric-permissions-api-v1.mixins.json:SignBlockEntity_2Mixin from mod legacy-fabric-permissions-api-v1] from phase [DEFAULT] in config [legacy-fabric-permissions-api-v1.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at net.minecraft.class_224.method_8995(class_224.java:141) ~[client-intermediary.jar:?]
	at net.minecraft.class_184.method_421(class_184.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_799.method_2170(class_799.java:292) ~[client-intermediary.jar:?]
	at net.minecraft.class_2107.method_7947(class_2107.java:507) ~[client-intermediary.jar:?]
	at net.minecraft.class_731.method_8037(class_731.java:59) ~[client-intermediary.jar:?]
	at net.minecraft.class_731.method_1831(class_731.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_2570$1.run(class_2570.java:22) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.class_1723.method_10652(class_1723.java:19) ~[client-intermediary.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field editor was not located in the target class net.minecraft.class_224$2. Using refmap legacy-fabric-permissions-api-v1-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at net.minecraft.class_224.method_8995(class_224.java:141) ~[client-intermediary.jar:?]
	at net.minecraft.class_184.method_421(class_184.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_799.method_2170(class_799.java:292) ~[client-intermediary.jar:?]
	at net.minecraft.class_2107.method_7947(class_2107.java:507) ~[client-intermediary.jar:?]
	at net.minecraft.class_731.method_8037(class_731.java:59) ~[client-intermediary.jar:?]
	at net.minecraft.class_731.method_1831(class_731.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_2570$1.run(class_2570.java:22) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.class_1723.method_10652(class_1723.java:19) ~[client-intermediary.jar:?]
	... 5 more

**Comment by Lonmo0208** [comment]
![NO_ADD_API](https://github.com/Legacy-Fabric/fabric/assets/95102577/621d7d73-0f08-4561-b28a-9885defd45f2)
![YES ADD API](https://github.com/Legacy-Fabric/fabric/assets/95102577/e692f3f4-9a6a-40fb-956b-8d71272d8cc6)

**Comment by thecatcore** [comment]
What is you minecraft version?

**Comment by Lonmo0208** [comment]
> 你的 minecraft 版本是什么？

1.8.9
However, it also appears in version 1.8
