### ISSUE TITLE
java.lang.AbstractMethodError when trying to render bossbar

### ISSUE THREAD

**Issue by BluCobalt** [Legacy-Fabric/fabric#46]
full crash: [here](https://hb.blucobalt.dev/elupazavis.coffeescript)

```Description: Rendering entity in world

java.lang.AbstractMethodError: net.minecraft.class_1880.f_()Lnet/minecraft/class_1444;
	at net.minecraft.class_1001.method_3301(class_1001.java:15)
	at net.minecraft.class_1179.method_4073(class_1179.java:23)
	at net.minecraft.class_1179.method_3910(class_1179.java:11)
	at net.minecraft.class_1135.method_3891(class_1135.java:295)
	at net.minecraft.class_1135.method_3893(class_1135.java:260)
	at net.minecraft.class_1135.method_3892(class_1135.java:227)
	at net.minecraft.class_1036.method_3527(class_1036.java:596)
	at net.minecraft.class_1012.method_3359(class_1012.java:1244)
	at net.minecraft.class_1012.method_3369(class_1012.java:1149)
	at net.minecraft.class_1012.method_3356(class_1012.java:1002)
	at net.minecraft.class_669.method_2286(class_669.java:915)
	at net.minecraft.class_669.method_2247(class_669.java:325)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

**Comment by BoogieMonster1O1** [comment]
This is a known issue. 
Initial take on fixing this is here: https://github.com/Legacy-Fabric/abstract-methods
It might not work, but it's worth a shot. 
[abstract-methods-0.1.0.jar.zip](https://github.com/Legacy-Fabric/fabric/files/5251100/abstract-methods-0.1.0.jar.zip)

**Comment by BluCobalt** [comment]
tried it and it didn't work

**Comment by BoogieMonster1O1** [comment]
> tried it and it didn't work

same error?
send the full log with the mod

**Comment by BluCobalt** [comment]
https://hastebin.com/cezakefeqa.coffeescript this is the crash i get with the mod

**Comment by BoogieMonster1O1** [comment]
> https://hastebin.com/cezakefeqa.coffeescript this is the crash i get with the mod

It looks like the mod doesn't help :( 
@shedaniel knows a solution to fix it without an extra mod; i'll try to get them to fix it

**Comment by BluCobalt** [comment]
awesome, thanks

**Comment by hYdos** [comment]
i know the solution but its a pain to fix. we need to fix intermediary inheritence.

**Comment by BluCobalt** [comment]
Is it the same issue as [this?](https://github.com/Legacy-Fabric/fabric-loader-1.8.9/issues/1)

**Comment by hYdos** [comment]
indeed

**Comment by BluCobalt** [comment]
@hYdos is quilt loader going to fix this

**Comment by hYdos** [comment]
> 
> 
> @hYdos is quilt loader going to fix this

This is not a loader issue. This is a intermediary issue. I will fix it when we migrate to quilt

**Comment by BluCobalt** [comment]
Is it not that intermediary inheritance thing? I thought that because boogie made that issue it was a loader problem

**Comment by hYdos** [comment]
it is technically a loader problem but if it is it should be delt with upstream.

**Comment by BluCobalt** [comment]
That is why I asked if it will be fixed by quilt loader

**Comment by arthurbambou** [comment]
Fixed by new intermediary
