### ISSUE TITLE
[bug] Client-side: Main class knotclient mising

### ISSUE THREAD

**Issue by shadichy** [Legacy-Fabric/fabric#57]

**Comment by hYdos** [comment]
Could you please give us more info?

**Comment by SUPERN00Bthefirst** [comment]
Info needed for this issue:
```
[20:02:35] [main/INFO]: Loading for game Minecraft 1.8.9
[20:02:36] [main/INFO]: [FabricLoader] Loading 21 mods: minecraft@1.8.9, fabric-networking-blockentity-v0@0.1.0+nogit, fabric-resource-loader-v0@0.2.3+nogit, fabric-commands-v1@0.1.0+nogit, fabric-gamerule-api-v1@1.0.1+nogit, fabricloader@0.9.3+build.202009100647, fabric-content-registries-v1@1.3.0+nogit, fabric-armor-api-v1@1.0.2+nogit, fabric-commands-v0@1.0.0+nogit, fabric-lifecycle-events-v1@1.1.2+nogit, fabric-object-builder-api-v1@1.0.2+nogit, fabric-crash-report-info-v1@0.1.2+nogit, fabric-events-lifecycle-v0@0.2.1+nogit, fabric-events-interaction-v0@0.4.4+nogit, fabric@0.9.1, fabric-recipes-v1@1.0.2+nogit, fabric-item-groups-v0@0.1.2+nogit, fabric-api-base@0.1.4+nogit, fabric-networking-v0@0.2.0+nogit, fabric-rendering-v1@1.0.2+nogit, fabric-key-binding-api-v1@1.0.1+nogit
[20:02:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/C:/Users/SUPERN00Bthe1/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.1+build.21/sponge-mixin-0.8.1+build.21.jar Service=Knot/Fabric Env=CLIENT
[20:02:36] [main/FATAL]: Mixin prepare failed preparing MixinKeyedResourceReloadListener$Client in fabric-resource-loader-v0.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'net.fabricmc.fabric.mixin.resource.loader.MixinKeyedResourceReloadListener$Client' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'net.fabricmc.fabric.mixin.resource.loader.MixinKeyedResourceReloadListener$Client' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:652) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:515) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-1.8.9-0.9.3+build.202009100647.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-1.8.9-0.9.3+build.202009100647.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148) [fabric-loader-1.8.9-0.9.3+build.202009100647.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-1.8.9-0.9.3+build.202009100647.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-1.8.9-0.9.3+build.202009100647.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-1.8.9-0.9.3+build.202009100647.jar:?]
Caused by: java.lang.ClassNotFoundException: The specified mixin 'net.fabricmc.fabric.mixin.resource.loader.MixinKeyedResourceReloadListener$Client' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1297) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:848) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	... 15 more
```

**Comment by shadichy** [comment]
no bro, i fixed it, please close
