### ISSUE TITLE
[bug] server-side: Crashing

### ISSUE THREAD

**Issue by shadichy** [Legacy-Fabric/fabric#58]
C:\Users\Administrator\Downloads\server>java -jar fabric-server-launch.jar
[13:24:31] [main/INFO]: Loading for game Minecraft 1.8.9
[13:24:31] [main/INFO]: [FabricLoader] Loading 2 mods: minecraft@1.8.9, fabriclo
ader@0.9.3+build.202009100647
[13:24:31] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:
/C:/Users/Administrator/Downloads/server/fabric-server-launch.jar Service=Knot/F
abric Env=SERVER
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric se
rver environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricSer
verLauncher.java:51)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception
occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricSe
rverLauncher.java:107)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricSer
verLauncher.java:49)
Caused by: java.lang.RuntimeException: An exception occurred when launching the
server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricS
erverLauncher.java:63)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricSe
rverLauncher.java:105)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricS
erverLauncher.java:61)
        ... 2 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetExcepti
on
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGamePr
ovider.java:196)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGamePr
ovider.java:194)
        ... 9 more
Caused by: java.lang.LinkageError: loader constraint violation: when resolving m
ethod "net.fabricmc.loader.guava.IteratorsFix.emptyListIterator()Lcom/google/com
mon/collect/UnmodifiableListIterator;" the class loader (instance of net/fabricm
c/loader/launch/knot/KnotClassLoader) of the current class, com/google/common/co
llect/EmptyImmutableSet, and the class loader (instance of net/fabricmc/loader/l
aunch/server/InjectingURLClassLoader) for the method's defining class, net/fabri
cmc/loader/guava/IteratorsFix, have different Class objects for the type com/goo
gle/common/collect/UnmodifiableListIterator used in the signature
        at com.google.common.collect.EmptyImmutableSet.iterator(EmptyImmutableSe
t.java:55)
        at com.google.common.collect.EmptyImmutableSet.iterator(EmptyImmutableSe
t.java:31)
        at net.minecraft.class_378$class_379.method_1235(class_378.java:160)
        at net.minecraft.class_378.<init>(class_378.java:55)
        at net.minecraft.class_160.method_714(class_160.java:909)
        at net.minecraft.class_160.<init>(class_160.java:276)
        at net.minecraft.class_160.<init>(class_160.java:281)
        at net.minecraft.class_144.<init>(class_144.java:13)
        at net.minecraft.class_160.method_633(class_160.java:941)
        at net.minecraft.class_1608.method_5897(class_1608.java:456)
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:645)
        ... 14 more

C:\Users\Administrator\Downloads\server>pause
Press any key to continue . . .

**Comment by hYdos** [comment]
this is a bug with the loader. to fix it you have to remove the com/google folder/package from the minecraft server jar

**Comment by shadichy** [comment]
thanks

**Comment by shadichy** [comment]
still not working

**Comment by hYdos** [comment]
sorry i made a mistake. please redownload the server jar and re-read the message

**Comment by shadichy** [comment]
can u send me a demo one please

**Comment by shadichy** [comment]
"Downloading 8/8MB
No valid  1.8.9 server jar found"

**Comment by hYdos** [comment]
thats normal

**Comment by hYdos** [comment]
> can u send me a demo one please

i cant do that. it would be illegal

**Comment by shadichy** [comment]
> > can u send me a demo one please
> 
> i cant do that. it would be illegal

why?

**Comment by shadichy** [comment]
now idk how 2 create a sv cuz it cant

**Comment by BoogieMonster1O1** [comment]
> > > can u send me a demo one please
> > 
> > 
> > i cant do that. it would be illegal
> 
> why?

https://launcher.mojang.com/v1/objects/b58b2ceb36e01bcd8dbf49c8fb66c55a9f0676cd/server.jar
use this

**Comment by shadichy** [comment]
thanks, i'll try

**Comment by shadichy** [comment]
still

**Comment by shadichy** [comment]
It doesn't work

**Comment by hYdos** [comment]
> this is a bug with the loader. to fix it you have to remove the com/google/common package from the minecraft server jar

^^^^^^^^^^^^^^^^^^^

**Comment by shadichy** [comment]
Maybe a separate repo for server-side only? :))

**Comment by shadichy** [comment]
> > this is a bug with the loader. to fix it you have to remove the com/google/common package from the minecraft server jar
> 
> ^^^^^^^^^^^^^^^^^^^

how? recompile?

**Comment by halotroop2288** [comment]
> how? recompile?
Just open it in 7-Zip and delete the package.

**Comment by shadichy** [comment]
> > how? recompile?
> 
> Just open it in 7-Zip and delete the package.

really? but i didnt use windows anymore,
any 7zip alt for linux?

**Comment by halotroop2288** [comment]
> any 7zip alt for linux?

Tar or your distro's archive explorer.

I'm surprised someone who doesn't know how to use an archiving tool can use Linux so confidently.

**Comment by shadichy** [comment]
> > any 7zip alt for linux?
> 
> Tar or your distro's archive explorer.
> 
> I'm surprised someone who doesn't know how to use an archiving tool can use Linux so confidently.

nah. i just think that jar file must be recompiled if i want it to work :v

**Comment by halotroop2288** [comment]
Definitely not.

**Comment by shadichy** [comment]
thanks i'll try

**Comment by shadichy** [comment]
now i know that jar's just zip :v bruh

**Comment by shadichy** [comment]
awesome, worked perfectly, thanks
