### ISSUE TITLE
[ BUG ] Crash on Hypixel Network

### ISSUE THREAD

**Issue by SUPERN00Bthefirst** [Legacy-Fabric/fabric#86]
Legacy Fabric version: 1.8.9-0.9.3+build.202009100647

Mods Equipped: 
- None

Expected Behaviour:
- Game will load as normal without crashing

Crash Report:
```
[20:37:14] [main/INFO]: Loading for game Minecraft 1.8.9
[20:37:15] [main/INFO]: [FabricLoader] Loading 2 mods: minecraft@1.8.9, fabricloader@0.9.3+build.202009100647
[20:37:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/C:/Users/SUPERN00Bthe1/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.1+build.21/sponge-mixin-0.8.1+build.21.jar Service=Knot/Fabric Env=CLIENT
[20:37:15] [Client thread/INFO]: Setting user: SUPERN00Bthe1
[20:37:15] [Client thread/INFO]: (Session ID is token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZGQxYjdjNWFhYzc5YmM2YjkxOTY2OTlkMzFhYmEzNCIsInlnZ3QiOiI3OWI3ZDI4YTgxODQ0YWJmOWI0ZjFmMjA4OWJjM2YwOSIsInNwciI6ImUwMTBiMzYyZGI5ZDQ5NGVhNmYwODI3YWIxMWRlNWViIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MTY5ODkwMjcsImlhdCI6MTYxNjgxNjIyN30.zU8yrWYva5cNFIar2f4tjlLk1WVsvWZ0C1RuF0lqdGg:e010b362db9d494ea6f0827ab11de5eb)
[20:37:17] [Client thread/INFO]: LWJGL Version: 2.9.4
[20:37:18] [Client thread/INFO]: Reloading ResourceManager: Default
[20:37:18] [Sound Library Loader/INFO]: Starting up SoundSystem...
[20:37:18] [Thread-6/INFO]: Initializing LWJGL OpenAL
[20:37:18] [Thread-6/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[20:37:18] [Thread-6/INFO]: OpenAL initialized.
[20:37:18] [Sound Library Loader/INFO]: Sound engine started
[20:37:19] [Client thread/INFO]: Created: 512x512 textures-atlas
[20:37:20] [Client thread/ERROR]: Realms module missing
java.lang.NoSuchMethodException: com.mojang.realmsclient.gui.screens.RealmsNotificationsScreen.<init>(net.minecraft.realms.RealmsScreen)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_51]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_51]
	at net.minecraft.realms.RealmsBridge.getNotificationScreen(RealmsBridge.java:33) [intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_765.method_2795(class_765.java:202) [intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_754.method_2786(class_754.java:376) [intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_669.method_2253(class_669.java:819) [intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_669.method_2277(class_669.java:476) [intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_669.method_2247(class_669.java:310) [intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:124) [intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194) [fabric-loader-1.8.9-0.9.3+build.202009100647.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-1.8.9-0.9.3+build.202009100647.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-1.8.9-0.9.3+build.202009100647.jar:?]
[20:37:26] [Client thread/INFO]: Connecting to mc.hypixel.net, 25565
[20:37:27] [Client thread/INFO]: [CHAT]                          
[20:37:28] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.class_1417: Rendering entity in world
	at net.minecraft.class_1135.method_3891(class_1135.java:329) ~[intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_1135.method_3893(class_1135.java:260) ~[intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_1135.method_3892(class_1135.java:227) ~[intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_1036.method_3527(class_1036.java:596) ~[intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_1012.method_3359(class_1012.java:1244) ~[intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_1012.method_3369(class_1012.java:1149) ~[intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_1012.method_3356(class_1012.java:1002) ~[intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_669.method_2286(class_669.java:915) ~[intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_669.method_2247(class_669.java:325) [intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:124) [intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194) [fabric-loader-1.8.9-0.9.3+build.202009100647.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-1.8.9-0.9.3+build.202009100647.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-1.8.9-0.9.3+build.202009100647.jar:?]
Caused by: java.lang.AbstractMethodError: net.minecraft.class_1880.method_8397()Lnet/minecraft/class_1444;
	at net.minecraft.class_1001.method_3301(class_1001.java:15) ~[intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_1179.method_4073(class_1179.java:23) ~[intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_1179.method_3910(class_1179.java:11) ~[intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	at net.minecraft.class_1135.method_3891(class_1135.java:295) ~[intermediary-fabric-loader-1.8.9-0.9.3+build.202009100647-1.8.9.jar:?]
	... 16 more
```

**Comment by BluCobalt** [comment]
This is a known issue, rendering the bossbar causes a crash. Please see #information in[ our discord](https://legacyfabric.net/discord) to see the (temporary) fix for this.
